### ISSUE TITLE
Is there a chance to bring back the manual pages?

### ISSUE THREAD

**Issue by voxik** [jeremyevans/tilt#7]
Is there a chance to bring back the manual pages, which were dropped in 7f5e6ddf55e97a9c24e13? I don't know the history behind, but I would not be surprised if they were introduced by request of somebody from Linux distribution community, because we were certainly delivering the manual pages in Fedora package and we are encouraged to do so by [guidelines](https://docs.fedoraproject.org/en-US/packaging-guidelines/#_manpages).

Of course there also other possibilities to ship the man pages, such as leveraging help2man, but that is a bit fragile in my experience.

**Comment by voxik** [comment]
BTW we were regenerating the manual pages by Ronn ourselves, so the *.ronn file would be enough for Fedora

**Comment by jeremyevans** [comment]
I think the reasoning for the removal was sound.  If we weren't even distributing the man page in the gem, there seems little point for keeping it, especially when it doesn't add information beyond what `tilt -h` gives you.

Few gems ship man pages, and few tilt users use the `tilt` command line tool.  I don't think it's worth keeping the man file, and having another development dependency.
