### ISSUE TITLE
"bin/tilt#test_0008_should support -y for layout file" test failure without erubi

### ISSUE THREAD

**Issue by voxik** [jeremyevans/tilt#8]
Trying to run the test suite on Fedora, I observe the following test error:

~~~
$ LANG=C.UTF-8 ruby -e 'Dir.glob "./test/**/*_test.rb", &method(:require)'

... snip ...

  1) Failure:
bin/tilt#test_0008_should support -y for layout file [/builddir/build/BUILD/tilt-2.2.0/usr/share/gems/gems/tilt-2.2.0/test/tilt_cli_test.rb:71]:
--- expected
+++ actual
@@ -1,4 +1,5 @@
 "Before
 Answer: 2
+
 After
 "
~~~

As you can see, I am running the test suite without using Bundler and therefore not having all dependencies available. As it turns out, installing erubi fixes the test error. Not sure if you want to make the test case more universal or if ERB as well as erubi should provide the same result.

BTW I don't think this is the right way to use assert_equal:

https://github.com/jeremyevans/tilt/blob/f4128e51a8101cf9d6729f4938c9ddde531b2dfe/test/tilt_cli_test.rb#L71

The correct way should be

~~~
    assert_equal "Before\nAnswer: 2\n\nAfter\n",  stdout
~~~

IOW the [expectation is supposed to be the first argument](https://www.rubydoc.info/gems/minitest/Minitest/Assertions#assert_equal-instance_method).

**Comment by jeremyevans** [comment]
Thanks for the report.  I'll fix this shortly.
